### ISSUE TITLE
Create release tag for QLoud qtchart commit 61b3662 ?

### ISSUE THREAD

**Issue by be1** [molke-productions/qloud#12]
Hello @molke-productions 
I Think this commit 61b36627ccb0f65e7935c6b729ba7e2a1b47064b marks a stable state of the **qtcharts** branch. Would you agree with me to set a tag for this ? Or maybe you prefer to merge later into master ? If you prefer not to merge, I would like to set a tag, but I don't know which name to set. Can you suggest me such a name ? v1.4-qtcharts ?

**Comment by molke-productions** [comment]
Yes, I agree. I only did some preliminary tests, but the qtcharts branch seems stable enough to warrant a new tag. I would prefer to merge this into the master branch (maybe after some clean-up: formatting, remove all qwt stuff, …). I don’t see a reason to keep the qwt version active. Unfortunately, I won’t get to it before the weekend due to work (and consequences of daylight saving ;-). Feel free to create a new branch after this if you have new ideas for further development.

**Comment by be1** [comment]
Oh yes, my QtCreator IDE does add 4 spaces instead of a TAB, I think this is wrong according to the original formatting. Sorry.

**Comment by be1** [comment]
Would you agree with me to tag it v1.3 (not alpha) ?

**Comment by molke-productions** [comment]
Considering the amount of changes, I would use v1.4 for the tag, but v1.3 is fine, too.

You are right, I do prefer tabs instead of spaces (and no more than 80 characters per line, …). Mainly, I use (manual) formatting just as a tool to better understand the structure.

**Comment by trebmuh** [comment]
Hi @be1 and @molke-productions 
Is the [1.4 qcharts version](https://github.com/molke-productions/qloud/releases/tag/v1.4) the new official release?
I'm a bit confused here.
Please confirm/infirm.

**Comment by molke-productions** [comment]
@trebmuh Setting the qtcharts branch as the release version was not exactly what I had in mind, but I’m fine with it. So, yes, you could call that an official release.

I did some clean-up of the qtcharts branch in the new **cleanup** branch now. This is mainly some formatting. I intend to merge this into the master branch as I see no reason to keep the Qwt version active. But before merging, I'll wait for someone to confirm that the new branch is working on systems other than my own, and keep this question open until then. This could be v1.4.1.

@be1 To get rid of my compiler warnings, I just repeated some default Qt::Alignment flags for `appendSeries()`. There is certainly a more elegant way of doing this (like optional arguments) since those are probably not used when there is no axis.
I did align the new buttons to the right, and the export button label is shortened to just “Export” as text export is not really limited to Gnuplot. The translation files are manually edited to account for the changes since I did not yet get around to try Qt Linguist.

**Comment by be1** [comment]
@molke-productions thank you for doing the cleanup work. I apologize for I have been so fast last week, and sometimes a bit dirty (like for `appendSeries()`). I had spare time so I took this opportunity to work for QLoud quite a lot. Next time I'll commit, I'll try to follow your format style (80 cols) and indent with tabs.

**Comment by be1** [comment]
By the way from my test, QLoud compiles and run on: 
- Manjaro ARM on an ARM cpu. Qt 5.15.1
- Ubutnu 20.10 on an x86_64 cpu. Qt 5.14.2
It should compile on older versions of Qt (at least 5.11 i think). QtCharts have been introduced in Qt 5.8.

**Comment by molke-productions** [comment]
Thanks for the confirmation (and nice to know that QLoud also works on ARM).

My compulsive formatting is mostly cosmetics. If you keep doing the actual dirty development, this should be fine. I would just have provided a little more patience for the actual release part.
